
grpc_addr: "10.0.59.166:50052"
listen_port: 4444
yaml_file: "p4info.yaml"
flask_addr: "flaskapp:5000"

switch_mac: "00:90:fb:70:65:a9"
cloud_1_ip_prefix: "10.0.112.0"
cloud_2_ip_prefix: "10.200.2.0"
cloud_1_ip: "10.0.112.10"
cloud_2_ip: "10.200.2.1"
cloud_1_mac: "fa:16:3e:ac:bd:65"
cloud_2_mac: "3c:fd:fe:bb:bd:d1"
switch_virtual_ip_1: "10.0.112.8"
switch_virtual_ip_2: "10.200.2.2"
switch_host_port: 132
host_1_ip: "10.211.211.57"
host_2_ip: "10.200.0.2"
host_1_mac: "08:36:c9:f3:6e:01"
host_2_mac: "3c:fd:fe:d8:b0:6d"