#! /usr/bin/env python

# Script to parse manifest.json

import os
import sys
import argparse
import json, jsonschema

parser=argparse.ArgumentParser()

parser.add_argument ("--pipe", action = 'store_true', default = None,
                     help="return pipe names")

parser.add_argument ("manifest_file", help="manifest.json to parse")
opts = parser.parse_args()

try:
    manifest_json = json.load(open(opts.manifest_file, 'r'))
    programs = manifest_json['programs']

    if len(programs) != 1:
        print "manifest-config only supports one program"
        sys.exit(1)

    pipelines = programs[0]['contexts']

    pipe_name = []

    for pipeline in pipelines:
        if opts.pipe is not None:
            pipe_name.append(pipeline['pipe'])

    if opts.pipe is not None:
        print ' '.join(pipe_name)
        sys.exit(0)

except Exception as e:
    print e
